network-instance:
  - name: default
    admin-state: enable
    interface: 
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0

    next-hop-groups:
      group: 
        - name: client2
          nexthop:
            - index: 0
              ip-address: 10.0.12.1
              failure-detection:
                enable-bfd:
                  local-address: 10.0.12.0
                  local-discriminator: 12
                  remote-discriminator: 21

    static-routes:
      route: 
        - prefix: 10.0.2.0/30
          next-hop-group: client2
        - prefix: 192.168.20.0/24
          next-hop-group: client2

bfd:
  subinterface: 
    - id: ethernet-1/2.0
      admin-state: enable

interface:
- admin-state: enable
  name: ethernet-1/1
  subinterface:
    - admin-state: enable
      description: To client1
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.1.1/30

- admin-state: enable
  name: ethernet-1/2
  subinterface:
    - admin-state: enable
      description: To srlinux2
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.12.0/31

- admin-state: enable
  name: ethernet-1/3
  subinterface:
    - admin-state: enable
      description: To srlinux3
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.13.0/31
- admin-state: enable
  name: ethernet-1/4
  subinterface:
    - admin-state: enable
      description: To k01
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 192.168.10.1/24