interface:
- admin-state: enable
  name: ethernet-1/1
  subinterface:
    - admin-state: enable
      description: To client2
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.2.1/30

- admin-state: enable
  name: ethernet-1/2
  subinterface:
    - admin-state: enable
      description: To srlinux1
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.12.1/31

- admin-state: enable
  name: ethernet-1/3
  subinterface:
    - admin-state: enable
      description: To srlinux3
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.23.0/31


network-instance:
  - name: default
    admin-state: enable
    interface: 
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0

    next-hop-groups:
      group: 
        - name: client1
          nexthop:
            - index: 0
              ip-address: 10.0.12.0
              failure-detection:
                enable-bfd:
                  local-address: 10.0.12.1

    static-routes:
      route: 
        - prefix: 10.0.1.0/30
          next-hop-group: client1

bfd:
  subinterface: 
    - id: ethernet-1/2.0
      admin-state: enable
