network-instance:
  - name: default
    admin-state: enable
    interface: 
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0

    next-hop-groups:
      group: 
        - name: client2
          nexthop:
            - index: 0
              ip-address: 10.0.12.1
              failure-detection:
                enable-bfd:
                  local-address: 10.0.12.0

    static-routes:
      route: 
        - prefix: 10.0.2.0/30
          next-hop-group: client2

bfd:
  - subinterface: ethernet-1/2.0
    admin-state: enable
        
