interface:
- admin-state: enable
  name: ethernet-1/1
  subinterface:
    - admin-state: enable
      description: To client2
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.2.1/30

- admin-state: enable
  name: ethernet-1/2
  subinterface:
    - admin-state: enable
      description: To srlinux1
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.12.1/31

- admin-state: enable
  name: ethernet-1/3
  subinterface:
    - admin-state: enable
      description: To srlinux3
      index: 0
      ipv4:
        admin-state: enable
        address:
          ip-prefix: 10.0.23.0/31
